# Generated by Django 4.2.7 on 2025-08-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('planning', 'Planning'), ('in-progress', 'In Progress'), ('completed', 'Completed'), ('on-hold', 'On Hold')], default='planning', max_length=20),
        ),
    ]
