# Generated by Django 5.0.1 on 2025-08-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_user_confirm_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='units_data',
            field=models.JSONField(default=[]),
        ),
    ]
