# Generated by Django 5.0.1 on 2025-08-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_task_units_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='units_data',
            field=models.JSONField(default=dict),
        ),
    ]
