
"""
Django settings for Kosavi_Project project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path
# from corsheaders.defaults import default_headers

# Retrieve JWT_SECRET_KEY from environment variable or use a default value
# JWT_SECRET_KEY = os.environ.get('JWT_SECRET_KEY', 'default-secret-key')

BASE_DIR = Path(__file__).resolve().parent.parent

# SECRET_KEY = JWT_SECRET_KEY
SECRET_KEY = 'django-insecure-btb+u1n=0)1w3rel+d7lzj-pfr$ti&32*+4hx7$9azspq6050c'

# DEBUG = True

DEBUG = False

ALLOWED_HOSTS = ['103.235.71.9', 'localhost', '127.0.0.1','0.0.0.0','kosavi.druvo.in']

# ALLOWED_HOSTS = ['*']


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'Kosaviapp',
    'corsheaders'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware'
]


# MIDDLEWARE = [
#         'django.middleware.security.SecurityMiddleware',
#         'corsheaders.middleware.CorsMiddleware',
#         'django.contrib.sessions.middleware.SessionMiddleware',
#         'django.middleware.common.CommonMiddleware',
#         'django.middleware.csrf.CsrfViewMiddleware',
#         'django.contrib.auth.middleware.AuthenticationMiddleware',
#         'django.contrib.messages.middleware.MessageMiddleware',
#         'django.middleware.clickjacking.XFrameOptionsMiddleware',
#         'corsheaders.middleware.CorsMiddleware',
#         # 'clientapp.core.middleware.CorsMiddleware',
# ]

# Access-Control-Allow-Origin: http://localhost:8000, http://103.235.71.9:8000

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# CORS_ALLOW_ALL_ORIGINS = True   
# CORS_ORIGIN_ALLOW_ALL = True

# CORS_ALLOW_HEADERS = default_headers + (
#     "custom-headers",
   
# )

# CORS_ORIGIN_WHITELIST = ("http://localhost:8000", "http://103.235.71.9:8000") 
    
CORS_ALLOW_HEADERS = [ '*' ] 
CORS_ALLOW_METHODSS = [ '*' ] 
# CORS_ALLOWED_ORIGINS = [ '*' ]

# CORS_ALLOW_ALL_ORIGINS = True
# CORS_ALLOWED_ORIGINS = [ "https://ssspl.dhruvatara.com","http://ssspl.dhruvatara.com:3001"]

# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:3000","http://103.235.71.9:3000","http://kosavi.druvo.in:3000","http://kosavi.druvo.in:8081",
    
 
# ]

CORS_ALLOWED_ORIGINS = [
    
    "https://kosavi.druvo.in"
 
]
# SECURE_SSL_REDIRECT = False
# CSRF_COOKIE_SECURE = False
# SESSION_COOKIE_SECURE = False

# SECURE_HSTS_SECONDS = 0
# SECURE_HSTS_INCLUDE_SUBDOMAINS = False
# SECURE_HSTS_PRELOAD = False

# SECURE_BROWSER_XSS_FILTER = True
# SECURE_CONTENT_TYPE_NOSNIFF = True
# X_FRAME_OPTIONS = 'DENY'
# CORS_ALLOW_METHODS = [
#     "DELETE",
#     "GET",
#     "OPTIONS",
#     "PATCH",
#     "POST",
#     "PUT",
# ]
# CORS_ALLOW_HEADERS = [
#     "accept",
#     "accept-encoding",
#     "authorization",
#     "content-type",
#     "dnt",
#     "origin",
#     "user-agent",
#     "x-csrftoken",
#     "x-requested-with",
#     "cache-control",
#     "pragma",
# ]



ROOT_URLCONF = 'Kosavi_Project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI_APPLICATION = 'client_project.wsgi.application'
WSGI_APPLICATION = 'Kosavi_Project.wsgi.application'
# ASGI_APPLICATION = 'Kosavi_Project.asgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        # 'NAME': 'demo',
        'NAME': 'kosavi',
        
        'USER': 'root',
        'PASSWORD': 'root',
        'HOST': 'localhost',
        'PORT': '3306'
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True
USE_L10N = True
USE_TZ = True

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
# MEDIA_ROOT = BASE_DIR/'media/'
MEDIA_ROOT = BASE_DIR/'media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# STATIC_ROOT = os.path.join(BASE_DIR, 'build', 'static')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [],
    'DEFAULT_PERMISSION_CLASSES': [],
}


LOGGING = {
    'version': 1,
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}